### ISSUE TITLE
Quickload fails when this mod is active

### ISSUE THREAD

**Issue by ways** [THE-GREAT-OVERLORD-OF-ALL-CHEESE/S-Cam-Plus#1]
Hi

I love the mod, especially ace mode. But recently quickload (loading a quick save) fails for me. The game freezes completely. I've tested without mods, with some mods. Turns out this mod is the problem. Do you have any idea what can cause it?

**Comment by THE-GREAT-OVERLORD-OF-ALL-CHEESE** [comment]
I have only just seen this, this isn't really the most convenient way to contact me, I'm active on the VTOL modding discord a lot more, Unlike the persistent s-cam settings, it seems the quick loading system simply keeps spamming the change camera mode function in a while loop until its the same as in the quicksave. I think this is silly so I'm just going to patch it out.
